{
  "hash": "c3d1ada2d3c24d1299ccf55af2a158dc",
  "result": {
    "markdown": "---\ndate: 2023-11-07\nlesson: Stat4\nthema: Komplexere Regressionsmethoden\nindex: 3\nformat:\n  html:\n    code-tools:\n      source: true\nknitr:\n    opts_chunk:\n        collapse: false\n---\n\n\n# Stat4: Lösung 4.2N\n\n- Download dieses Lösungsscript via \"\\</\\>Code\" (oben rechts)\n- [Lösungstext als Download](Statistik_Loesung_4.2N.pdf)\n\n## Musterlösung Aufgabe 4.2N: Multiple logistische Regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"readr\")\n\npolis <- read_delim(\"datasets/stat1-4/polis.csv\", \",\")\npolis\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 19 × 4\n    ...1 ISLAND     RATIO    PA\n   <dbl> <chr>      <dbl> <dbl>\n 1     1 Bota       15.4      1\n 2     2 Cabeza      5.63     1\n 3     3 Cerraja    25.9      1\n 4     4 Coronadito 15.2      0\n 5     5 Flecha     13.0      1\n 6     6 Gemelose   18.8      0\n 7     7 Gemelosw   31.0      0\n 8     8 Jorabado   22.9      0\n 9     9 Mitlan     12.0      0\n10    10 Pata       11.6      1\n11    11 Piojo       6.09     1\n12    12 Smith       2.28     1\n13    13 Ventana     4.05     1\n14    14 Bahiaan    59.9      0\n15    15 Bahiaas    63.2      0\n16    16 Blanca     22.8      0\n17    17 Pescador   23.5      0\n18    18 Angeldlg    0.21     1\n19    19 Mejia       2.55     1\n```\n:::\n\n```{.r .cell-code}\nstr(polis)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspc_tbl_ [19 × 4] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ ...1  : num [1:19] 1 2 3 4 5 6 7 8 9 10 ...\n $ ISLAND: chr [1:19] \"Bota\" \"Cabeza\" \"Cerraja\" \"Coronadito\" ...\n $ RATIO : num [1:19] 15.41 5.63 25.92 15.17 13.04 ...\n $ PA    : num [1:19] 1 1 1 0 1 0 0 0 0 1 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   ...1 = col_double(),\n  ..   ISLAND = col_character(),\n  ..   RATIO = col_double(),\n  ..   PA = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n\n```{.r .cell-code}\nsummary(polis)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      ...1         ISLAND              RATIO             PA        \n Min.   : 1.0   Length:19          Min.   : 0.21   Min.   :0.0000  \n 1st Qu.: 5.5   Class :character   1st Qu.: 5.86   1st Qu.:0.0000  \n Median :10.0   Mode  :character   Median :15.17   Median :1.0000  \n Mean   :10.0                      Mean   :18.74   Mean   :0.5263  \n 3rd Qu.:14.5                      3rd Qu.:23.20   3rd Qu.:1.0000  \n Max.   :19.0                      Max.   :63.16   Max.   :1.0000  \n```\n:::\n:::\n\n\nMan erkennt, dass polis 19 Beobachtungen von drei Parametern enthält, wobei ISLAND ein Faktor mit den Inselnamen ist, während RATIO metrisch ist und PA nur 0 oder 1 enthält. Prädiktorvariable ist RATIO, abhängige Variable PA, mithin ist das korrekte statistische Verfahren eine logistische Regression (GLM).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Explorative Datenanalyse\nboxplot(polis$RATIO)\n```\n\n::: {.cell-output-display}\n![](Statistik4_Loesung_2n_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nDer Boxplot  zeigt zwei starke Ausreisser, ist also etwas rechtsschief. Da es sich aber um die unabhängige Variable handelt, muss uns das nicht weiter stören.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Definition des logistischen Modells\nglm.1 <- glm(PA ~ RATIO, family = \"binomial\", data = polis)\nsummary(glm.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = PA ~ RATIO, family = \"binomial\", data = polis)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.6067  -0.6382   0.2368   0.4332   2.0986  \n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)  \n(Intercept)   3.6061     1.6953   2.127   0.0334 *\nRATIO        -0.2196     0.1005  -2.184   0.0289 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 26.287  on 18  degrees of freedom\nResidual deviance: 14.221  on 17  degrees of freedom\nAIC: 18.221\n\nNumber of Fisher Scoring iterations: 6\n```\n:::\n:::\n\n\nModell ist signifikant (p-Wert in Zeile RATIO ist < 0.05). Jetzt müssen wir noch prüfen, ob es auch valide ist:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Modelldiagnostik für das gewählte Modell (wenn nicht signifikant, dann OK)\n1 - pchisq(glm.1$deviance, glm.1$df.resid)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6514215\n```\n:::\n\n```{.r .cell-code}\n# Visuelle Inspektion der Linearität\nlibrary(\"car\")\ncrPlots(glm.1, ask = F)\n```\n\n::: {.cell-output-display}\n![](Statistik4_Loesung_2n_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nBeide Aspekte sind OK, d.h. der Test war nicht signifikant und die pinkfarbene Linie liegt fast auf der theoretischen Linie (blau gestrichelt).\n\nJetzt brauchen wir noch die Modellgüte (Pseudo-R2):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Modellgüte (pseudo-R²)\n1 - (glm.1$dev / glm.1$null)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4590197\n```\n:::\n:::\n\n\nUm zu unser Modell zu interpretieren müssen wir noch in Betracht ziehen, dass wir nicht die Vorkommenswahrscheinlichkeit selbst, sondern logit (Vorkommenswahrscheinlichkeit) modelliert haben. Unser Ergebnis (die beiden Parameterschätzungen von oben, also 3.6061 und -0.2196) muss also zunächst in etwas Interpretierbares übersetzt werden:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Steilheit der Beziehung in Modellen mit nur einem Parameter\nexp(glm.1$coef[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    RATIO \n0.8028734 \n```\n:::\n:::\n\n\n< 1, d. h. Vorkommenswahrscheinlichkeit sinkt mit zunehmender Isolation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LD50 für 1-Parameter-Modelle (hier also x-Werte, bei der 50% der Inseln besiedelt sind)\n-glm.1$coef[1] / glm.1$coef[2]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept) \n    16.4242 \n```\n:::\n:::\n\n\nAm besten stellen wir auch unsere Funktionsgleichung dar. Dazu müssen wir das „Rohergebnis“ (mit P = Vorkommenswahrscheinlichkeit)\n\nln (P/ (1- P)) = 3.606 – 0.220 RATIO\n\nso umformen, dass wir links nur P stehen haben:\n\nP = exp (3.606 – 0.220 RATIO) / (1 + exp (3.606 – 0.220 RATIO))\n\nDas ist also unsere vorhergesagte Regressionsfunktion, die wir in einem letzten Schritt auch noch visualisieren können (und sollten):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ergebnisplots\npar(mfrow = c(1, 1))\n\nxs <- seq(0, 70, l = 1000)\nglm.predict <- predict(glm.1, type = \"response\", se = T, newdata = data.frame(RATIO = xs))\n\nplot(PA ~ RATIO, data = polis, xlab = \"Umfang-Flächen-Verhältnis\", ylab = \"Vorkommenswahrscheinlichkeit\", pch = 16, col = \"red\")\npoints(glm.predict$fit ~ xs, type = \"l\")\nlines(glm.predict$fit + glm.predict$se.fit ~ xs, type = \"l\", lty = 2)\nlines(glm.predict$fit - glm.predict$se.fit ~ xs, type = \"l\", lty = 2)\n```\n\n::: {.cell-output-display}\n![](Statistik4_Loesung_2n_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "Statistik4_Loesung_2n_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}