{
  "hash": "bc92c222c524c1dae62d812b6d73b6bd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ndate: 2023-10-30\nlesson: Stat1\nthema: Grundlagen der Statistik\nformat:\n  html:\n    code-tools:\n      source: true\nknitr:\n  opts_chunk:\n    collapse: false\n---\n\n\n\n\n# Stat1: Lösung\n\n- Download dieses Lösungsscript via \"\\</\\>Code\" (oben rechts)\n\n## Musterlösung Übung 1.1: Assoziationstest\n\nIn diesem Beispiel soll einem Klischee auf den Grund gegagen werden: **Sind Aargauer überdurchschnittlich mit weissen Socken assoziiert?** Die Datenerhebung basiert auf männlichen Studenten bei denen folgende beiden binären Variablen erhoben wurden:\n\n- Sockenfarbe: weiss, nicht-weiss\n- Selbstdeklarierte Kantonsangehörigkeit: AG, nicht-AG\n\nDie Hypothese ist: Das Klischee trifft zu, weisse Socken sind überdurchschnittlich häufig mit Aargauer Studenten assoziiert.\n\nDie Datenerhebung unter 35 Studenten ergab folgende Datengrundlage:\n\n- Weisssockige Aargauer: 4\n- Nicht-weisssockige Aargauer: 2\n- Weissockige nicht-Aargauer: 7\n- Nicht-weisssockige nicht-Aargauer: 22\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Matrix erstellen\nAargauer <- c(4, 2)\nnames(Aargauer) <- c(\"Weiss\", \"NotWeiss\")\nNotAargauer <- c(7, 22)\nnames(NotAargauer) <- c(\"Weiss\", \"NotWeiss\")\nAGsocks <- data.frame(Aargauer, NotAargauer)\nAGsocks <- as.matrix(AGsocks)\nAGsocks\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Aargauer NotAargauer\nWeiss           4           7\nNotWeiss        2          22\n```\n\n\n:::\n\n```{.r .cell-code}\n# Daten anschauen mit erstem Google-Ergebnis für \"Assoziation Plot r\"\nassocplot(AGsocks) # Interpretation des Plots mit dem Befehl ?assocplot\n```\n\n::: {.cell-output-display}\n![](Statistik1_Loesung_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n\nDer Assoziationsplot zeigt, dass in den Daten weisse Socken bei den Aargauern überverterten und bei den Nicht-Aargauern untervertreten sind.\n\nFür kleine Erwartungswerte in den Zellen (\\< 5) ist der Chi-Quadrat-Test nicht zuverlässig (siehe \"Warning message\"). Darum wird mit Fishers exaktem Test gearbeitet.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Tests durchführen\nchisq.test(AGsocks) # Chi-Quadrat-Test nur zum anschauen.\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  AGsocks\nX-squared = 2.4323, df = 1, p-value = 0.1189\n```\n\n\n:::\n\n```{.r .cell-code}\nfisher.test(AGsocks) # \"Fisher's Exact Test for Count Data\"\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  AGsocks\np-value = 0.06323\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n  0.6811227 78.4336189\nsample estimates:\nodds ratio \n  5.897263 \n```\n\n\n:::\n:::\n\n\n\n\n### Ergebnisse\n\nIn den erhobenen Daten konnte keine signifikante Assoziation zwischen Kantonangehörigkeit (AG, nicht-AG) und Sockenfarbe (weiss, nicht-weiss) festgestellt werden. Der *p*-Wert von Fishers exaktem Test war nur marginal signifikant (*p* = 0.063). Das nicht-signfikante Resultat überrascht auf den ersten Blick, denn der \"odds ratio\" im Datensatz ist mit 5.9 relativ hoch und 67 % der Aargauer trugen weisse Socken während nur 24 % der Nicht-Aargauer weisse Socken trugen. Doch war der Anteil von nur 6 Aargauer in der nur 35 Männer umfassenden Stichprobe relativ klein, um ein verlässliches Bild der Sockenpräferenzen der Aargauer zu machen. Insofern leuchtet es ein, das bei dieser kleinen und unausgewogenen Stichprobe die \"Power\" des satistischen Tests (um die Nullhypothese zu verwerfen) relativ klein ist.\n\n## Musterlösung Übung 1.2: t-Test\n\n> Leseempfehlung Kapitel 2 von [Manny Gimond](https://mgimond.github.io/Stats-in-R/z_t_tests.html)\n\n### Null- und Alternativhypothese\n\n$H_0$: Es gibt keinen Unterschied in den Verkaufszahlen zwischen den Basis- und den Interventionswochen.\n\n$H_1$: Es gibt einen Unterschied in den Verkaufszahlen zwischen den Basis- und den Interventionswochen.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# lade Daten\ndf <- readr::read_delim(\"datasets/stat1-4/Datensatz_novanimal_Uebung_Statistik1.2.csv\", delim = \";\")\n\n# überprüft die Voraussetzungen für einen t-Test\nggplot(df, aes(x = condit, y = tot_sold)) + # achtung 0 Punkt fehlt\n  geom_boxplot(fill = \"white\", color = \"black\", size = 1) +\n  labs(x = \"\\nBedingungen\", y = \"Durchschnittlich verkaufte Gerichte pro Woche\\n\") +\n  mytheme\n```\n\n::: {.cell-output-display}\n![](Statistik1_Loesung_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Auf den ersten Blick scheint es keine starken Abweichungen zu einer\n# Normalverteilung zu geben resp. es sind keine extremen schiefen Verteilungen\n# ersichtlich (vgl. Skript Statistik 2)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# führt einen t-Tests durch;\n# es wird angenommen, dass die Verkaufszahlen zwischen den Bedingungen\n# unabhängig sind\n\nt_test <- t.test(tot_sold ~ condit, data = df, var.equl = T)\nt_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  tot_sold by condit\nt = 0.27168, df = 9.9707, p-value = 0.7914\nalternative hypothesis: true difference in means between group Basis and group Intervention is not equal to 0\n95 percent confidence interval:\n -115.2743  147.2743\nsample estimates:\n       mean in group Basis mean in group Intervention \n                      2203                       2187 \n```\n\n\n:::\n\n```{.r .cell-code}\n# alternative Formulierung\nt.test(\n  df[df$condit == \"Basis\", ]$tot_sold,\n  df[df$condit == \"Intervention\", ]$tot_sold\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  df[df$condit == \"Basis\", ]$tot_sold and df[df$condit == \"Intervention\", ]$tot_sold\nt = 0.27168, df = 9.9707, p-value = 0.7914\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -115.2743  147.2743\nsample estimates:\nmean of x mean of y \n     2203      2187 \n```\n\n\n:::\n:::\n\n\n\n\n### Methoden\n\nUnser Ziel bestand darin, einen Vergleich der aggregierten Verkaufszahlen zwischen den Interventions- und Basiswochen durchzuführen. Wir gingen davon aus, dass die wöchentlichen Verkaufszahlen unabhängig voneinander sind, weshalb wir die Unterschiede zwischen den Verkaufszahlen pro Woche in den beiden Bedingungen mittels eines t-Tests untersuchten. Obwohl bei der visuellen Prüfung der Modellvoraussetzungen keine schwerwiegenden Verletzungen festgestellt wurden (abgesehen von einem Ausreißer), entschieden wir uns dennoch für einen Welch t-Test. Es sei angemerkt, dass die Gruppengröße mit jeweils n = 6 Wochen eher klein war. Trotzdem erzielten die T-Tests verlässliche Ergebnisse. Für weitere Informationen zu diesem Thema verweisen wir auf die verlinkte [Studie](https://scholarworks.umass.edu/cgi/viewcontent.cgi?article=1307&context=pare).\n\n\n\n\n### Ergebnisse\n\nIn den Basiswochen werden wöchentlich mehr Gerichte verkauft als in den Interventionswochen, wie in Abbildung 1 ersichtlich ist. Allerdings ergab der Welch t-Test, dass es keine signifikanten Unterschiede in den wöchentlichen Verkaufszahlen zwischen den beiden Bedingungen (*t*(10) = 0.272 , *p* = 0.791). m die Ergebnisse weiter zu bestätigen, könnte eine $\\chi^2$-Test durchgeführt werden, da die Gruppengröße mit n = 6 als eher klein betrachtet werden kann.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Die wöchentlichen Verkaufszahlen für die Interventions- und Basiswochen unterscheiden sich nicht signifikant.](Statistik1_Loesung_files/figure-html/fig-ggplot-boxplot-final-1.png){#fig-ggplot-boxplot-final width=80%}\n:::\n:::\n",
    "supporting": [
      "Statistik1_Loesung_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}